config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meches
  resources :carriers
  resources :weapons
  resources :battles
  resources :matches

  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout',  to: 'sessions#destory', via: 'delete'
  match '/active', to: 'users#active', via: 'get'
  match '/about', to: 'home#about', via: 'get'
  match '/aboutus', to:'home#aboutus',via: 'get'
  match '/join', to: 'home#join', via: 'get'
  match '/achieve', to: 'home#achieve', via: 'get'
  match '/mechlist', to: 'meches#mech_list', via: 'get'
  match '/reactive', to: 'users#re_active',via: 'get'
  match '/gamebg',to: 'home#gamebg', via: 'get'
  match '/newer',to: 'home#newer', via: 'get'
  match '/download',to: 'home#download', via: 'get'
  match '/stat', to: 'home#stat',via: 'get'
  match '/opensource', to: 'home#opensource', via: 'get'

  match '/users/followed/:id', to: 'users#followed', via: 'get', as: :followed
  match '/users/follower/:id', to: 'users#follower', via: 'get', as: :follower

  match '/meches/stop/:id', to: 'users#stop', via: 'post', as: :stop_mech
  match '/meches/start/:id', to: 'users#start', via: 'post', as: :start_mech

  match '/following/:followed_id', to: 'users#following',via: 'post', as: :follow_user
  match '/unfollowing/:unfollowed_id', to: 'users#unfollowing', via: 'post', as: :unfollow_user

  match '/matches/apply/:id', to: 'matches#apply', via: 'post'
  match '/matches/addmech/:id/:mech_id', to: 'matches#addmech', via: 'post'
  match '/matches/result/:id', to: 'matches#result', via: 'get', as: :match_result
  match '/matches/video/:id', to: 'matches#video', via: 'get', as: :match_rvideo
  match '/matches/genracecard/:id', to: 'matches#gen_racecard', via: 'post', as: :gen_match_racecard
  match '/matches/racecard/:id', to: 'matches#racecard', via: 'get', as: :match_racecard

  match '/battles/download/:id', to: 'battles#download', via: 'get', as: :download_video
  match '/battles/star/:id', to: 'battles#star', via: 'post', as: :star_battle
  match '/battle/:defender_id/:attacker_id', to: 'battles#create', via: 'post'

  match '/video/:id', to: 'home#vedio', via: 'get'
  match '/wondervedio/:id', to: 'home#wondervedio', via: 'get', as: :wonder_vedio
  match '/highlights', to: 'home#wonderful',via: 'get'
end

app/models/user.rb
class User
  include Mongoid::Document
  # include Mongoid::MagicCounterCache
  Mongoid.raise_not_found_error = false
  include ActiveModel::SecurePassword

  field :name, type: String
  field :email, type: String
  field :motto, type: String
  field :status, type: String
  field :remember_token, type: String
  field :active_code, type: String
  field :is_actived, type: Boolean
  field :admin, type: Boolean
  field :join_time, type: DateTime
  field :meches_count, type: Integer, default: -> { 0 }
  field :sex, type: String
  field :blog, type: String
  field :battle_count, type: Integer, default: -> { 0 }
  field :win_times, type: Integer, default: -> { 0 }
  field :fail_times, type: Integer, default: -> { 0 }
  field :score, type: Integer, default: -> { 1500 }
  field :draw_times, type: Integer, default: -> { 0 }

  field :password_digest, type: String

  has_and_belongs_to_many :following, class_name: 'User'
  has_and_belongs_to_many :follower, class_name: 'User'

  has_and_belongs_to_many :matches

  has_and_belongs_to_many :battles, class_name: 'Battle', inverse_of: :users
  # counter_cache :battles
  
  has_and_belongs_to_many :stareds, class_name: 'Battle', inverse_of: :starers

  has_many :meches
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { maximum: 50 }
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

  validates :password, presence: true,
                       length: { minimum: 6 },
                       if: :password

  index({ email: 1, remember_token: 1 })

  before_save{ self.email = email.downcase }
  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash_custom(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def meches_per_page(page)
    self.meches.order("create_at DESC").page(page).per(2)
  end

  private

    def create_remember_token
      self.remember_token = User.hash_custom(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follower, :followed]
  before_action :signed_in_user, only: [:edit, :update, :admin, :following, :unfollowing, :re_active]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :admin]
  before_action :actived_user, only: [:update,:following,:unfollowing]
  before_action :locked_user
  # GET /users
  # GET /users.json
  def index
    @users = User.order_by(:meches_count.desc, :score.desc).page(params[:page]).per(30)
    @page = params[:page].nil? ? 1 : params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show
    store_location
  end

  # GET /users/new
  def new
    store_location
    if !signed_in?
      @user = User.new
    else
      flash[:warning] = "您已登录，请退出后再进行注册操作！"
      redirect_back_or current_user
    end
  end

  def re_active
    if !current_user.is_actived && UserMailer.signup_confirm_email(current_user).deliver
      flash[:warning] = "邮件发送成功，请登录您的注册邮箱查看!如未收到激活邮件，请使用注册邮箱发送任意信息到active@mechempire.cn激活"
      redirect_to current_user
    else
      flash[:warning] = "邮件发送失败, 请重试, 如多次未成功请联系管理员!"
      redirect_to current_user
    end
  end

  # GET /users/1/edit
  def edit
    store_location
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    @user.name = @user.email.split("@")[0].titleize
    @user.active_code = rand(Time.now.to_i).to_s
    @user.is_actived = false
    @user.admin  = false
    @user.join_time = Time.now
    @user.is_actived = true

    respond_to do |format|
      if @user.save
        # UserMailer.signup_confirm_email(@user).deliver
        sign_in @user

        format.html { redirect_to @user, notice: '注册成功，感谢您注册本站!' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to edit_user_path(@user), notice: '个人信息更新成功!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '删除用户成功!' }
      format.json { head :no_content }
    end
  end

  def active
    @user = User.find_by(name:params[:name])
    if @user != nil && !@user.is_actived && @user.active_code == params[:active_code]
      @user.update_attribute(:is_actived, true)
      flash[:success] = "恭喜您，您已经成功激活了您的账户！"
    elsif @user != nil && @user.is_actived
      flash[:warning] = "您的账户已经处于激活状态，请勿重复激活！"
    else
      flash[:danger] = "激活失败！"
    end

    redirect_to root_path
  end

  def following
    followed_user = User.find(params['followed_id'])

    respond_to do |format|
      unless followed_user.nil?
        unless current_user.following.include?(followed_user)
          current_user.following.push(followed_user)
          followed_user.follower.push(current_user)
          @user = followed_user
          @follower_count = current_user.following.count
          format.js
        else
          format.js do
            render js: "alert('已关注，请勿重新关注！');"
          end
        end
      else
        format.js do
          render js: "alert('关注用户不存在！');"
        end
      end
    end
  end

  def unfollowing
    unfollowed_user = User.find(params['unfollowed_id'])

    respond_to do |format|
      unless unfollowed_user.nil?
        if current_user.following.include?(unfollowed_user)
          current_user.following.delete(unfollowed_user)
          unfollowed_user.follower.delete(current_user)
          @user = unfollowed_user
          @follower_count = current_user.following.count
          format.js
        else
          render js: "alert('未关注，请先关注！');"
        end
      else
        format.js do
          render js: "alert('取关用户不存在！');"
        end
      end
    end
  end

  def follower
  end

  def followed
  end

  private
    def set_user
      @user = User.find(params[:id])
      if @user.nil?
        render :file => 'public/404.html'
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def user_params
      params.require(:user).permit(:name, 
                                   :email, 
                                   :password, 
                                   :password_confirmation,
                                   :sex,
                                   :motto,
                                   :blog)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=retro"
    image_tag(gravatar_url, alt: user.name, class: "img-thumbnail")
	end

  def gravater_url(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=retro"
  end
end

app/views/users/_active.html.erb
<%= link_to("点击重新发送激活邮件", "/reactive" , :class => "btn cuntom-btn btn-lg reactive") %>
<br><br>
<small>经测试部分邮箱有收不到激活邮件的情况，如遇到请使用注册邮箱发送任意消息到管理员邮箱激活：active@mechempire.cn </small>

app/views/users/_change_password.html.erb
<%= form_for(@user) do |f|%>
  <%= render 'shared/error_messages' %>
  <div class="form-group row">
    <div class="col-md-2">
      <%= f.label :password, :value => "密 码:"%>
    </div>
    <div class="col-md-10">
      <%= f.password_field :password , :class => "form-control", :placeholder => "请输入最短六位的密码"%>
    </div> 
  </div>
  <div class="form-group row">
    <div class="col-md-2">
      <%= f.label :password_confirmation, :value => "确认密码:"%>
    </div>
    <div class="col-md-10">
      <%= f.password_field :password_confirmation , :class => "form-control", :placeholder => "请输入确认密码"%>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
      <%= f.submit :class => "btn btn-success", :value => "确认修改" %>
    </div>
  </div>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_for(@user) do |f|%>
  <%= render 'shared/error_messages' %>
  
  <div class="form-group">
    <%= f.label :email , :value => "邮 箱:"%><br>
    <%= f.email_field :email , :class => "form-control", :placeholder => " 请输入注册邮箱"%>
  </div>
  <div class="form-group">
    <%= f.label :password, :value => "密 码:"%><br>
    <%= f.password_field :password , :class => "form-control", :placeholder => "请输入最短六位的密码"%>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :value => "确认密码:"%><br>
    <%= f.password_field :password_confirmation , :class => "form-control", :placeholder => "请输入确认密码"%>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-success btn-block", :value => "立即注册" %>
  </div>
<% end %>
<p class="new_user" style="text-align:right">已有账号，<%= link_to "立即登录" , signin_path%></p>

app/views/users/_user.html.erb
<li>
  <div class="col-md-4 battle-info">
    <!-- 帮忙写一下分支吧，分成第一、第二、第三、其他前八和非前八的用户 -->
    <!-- 然后给个排名变量 -->
    <div class="col-md-2 user-list-info">
      <span class="glyphicon user-rank-other" aria-hidden="true"></span>
    </div>
    <div class="col-md-10">
      <%= gravatar_for user, size: 52 %>
      &nbsp;
      <%= link_to user.name.truncate(10), user %> <br>
      <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
      <%= link_to "删除用户", user, method: :delete,
                                    data: { confirm: "确认删除用户吗？" } %>
        <% if !user.is_actived %>
          <small>未激活</small>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-1 user-list-info">
    机甲 <br>
    <%= user.meches.count %>
  </div>
  <div class="col-md-1 user-list-info">
    战斗 <br>
    <%= user.battle_count %>
  </div>
  <div class="col-md-1 user-list-info">
    胜利 <br>
    <%= user.win_times %>
  </div>
  <div class="col-md-1 user-list-info">
    积分 <br>
    <%= user.score %>
  </div>
  <div class="col-md-3 user-list-info">
    <% unless user.motto.nil? %>
      <%= user.motto %>
    <% end %>
  </div>
  <div class="col-md-1 user-list-info">
    <% unless current_user?(user) %>
      <% unless current_user.nil? %>
        <% unless(current_user.following.include?(user)) %>
          <%= link_to "关注", follow_user_path(user), remote: true, method: :post, :class => "btn btn-sm custom-btn pull-right", :id => "following-#{user._id}" %>
        <% else %>
          <%= link_to "取消关注", unfollow_user_path(user), remote: true, method: :post, :class => "btn btn-sm custom-btn pull-right", :id => "following-#{user._id}" %>
        <% end %>
      <% else %>
        <%= link_to "关注", signin_path, :class => "btn btn-sm custom-btn pull-right" %>
      <% end %>
    <% end %>
  </div>
</li>

app/views/users/destory.html.erb
<h1>Users#destory</h1>
<p>Find me in app/views/users/destory.html.erb</p>

app/views/users/followed.html.erb
<center class="container main-body">
  <h1><%= @user.name%> 关注了</h1>
  <ul class="users">
    <%= render @user.following %>
  </ul>
</center>

app/views/users/index.html.erb
<center class="container main-body custom-well">
  <h1>英雄榜</h1>
  
  <ul class="users">
    <%#= render @users %>
    <% @users.each.with_index do |user, index| %>
      <li>
        <div class="col-md-4 col-sm-6 col-xs-12 battle-info">
          <%#= @page %>
          <% if ( @page.to_i == 1 ) && ( index < 8 ) %>
            <%# 前八，加图标并向左缩进1em %>
            <div class="col-md-3 col-sm-3 col-xs-12 user-list-info top-users">
              <% if index == 0 %>
                <%# 金 %>
                <span class="glyphicon glyphicon-glass user-rank-1" aria-hidden="true"></span>
              <% elsif index == 1 %>
                <%# 银 %>
                <span class="glyphicon glyphicon-glass user-rank-2" aria-hidden="true"></span>
              <% elsif index == 2 %>
                <%# 铜 %>
                <span class="glyphicon glyphicon-glass user-rank-3" aria-hidden="true"></span>
              <% else %>
                <%# 其他前八 %>
                <span class="glyphicon glyphicon-star user-rank-other" aria-hidden="true"></span>
              <% end %>
              <%= (@page.to_i - 1) * 30 + (index + 1) %>
            </div>
          <% else %>
            <%# 非前八，无图标 %>
            <div class="col-md-3 col-sm-3 col-xs-12 user-list-info">
              &nbsp;<%= (@page.to_i - 1) * 30 + (index + 1) %>
            </div>
          <% end %>

          <div class="col-md-9 col-sm-9 col-xs-12">
            <%= gravatar_for user, size: 52 %>
            &nbsp;
            <%= link_to user.name.truncate(10), user %> <br>
            <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
            <%= link_to "删除用户", user, method: :delete,
                                          data: { confirm: "确认删除用户吗？" } %>
              <% if !user.is_actived %>
                <small>未激活</small>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="col-md-3 col-sm-3 col-xs-3 user-list-info">
            机甲 <br>
            <%= user.meches.count %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3 user-list-info">
            战斗 <br>
            <%= user.battle_count %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3 user-list-info">
            胜利 <br>
            <%= user.win_times %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3 user-list-info">
            积分 <br>
            <%= user.score %>
          </div>
        </div>
        <div class="col-md-4 col-sm-12 col-xs-12">
          <div class="col-md-9 col-sm-9 col-xs-9 user-list-info">
            <% unless user.motto.nil? %>
              <%= user.motto.truncate(40) %>
            <% end %>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-3 user-list-info">
            <% unless current_user?(user) %>
              <% unless current_user.nil? %>
                <% unless(current_user.following.include?(user)) %>
                  <%= link_to "关注", follow_user_path(user), remote: true, method: :post, :class => "btn btn-sm custom-btn pull-right", :id => "following-#{user._id}" %>
                <% else %>
                  <%= link_to "取消关注", unfollow_user_path(user), remote: true, method: :post, :class => "btn btn-sm custom-btn pull-right", :id => "following-#{user._id}" %>
                <% end %>
              <% else %>
                <%= link_to "关注", signin_path, :class => "btn btn-sm custom-btn pull-right" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <%= paginate @users, :outer_window => 2 %>
</center>

app/views/users/show.html.erb
<div class="custom-container main-body">
  <div class="row">
    <div class="col-md-3 custom-well">
      <%=link_to gravatar_for(@user, size: 240), @user , :class => "thumbnail" %>
      <h3 class="user-info-name">
        <%= @user.name %> 
        <small>
          <% if @user.sex == "boy" %>
            <i class="fa fa-mars"></i>
          <% elsif @user.sex == "girl" %>
            <i class="fa fa-venus"></i>
          <% end %>
        </small>
        <% if !@user.is_actived %>
          <small>未激活</small>
        <% end %>
        <% if @user.status == "LOCKED" %>
          <small>用户被锁定</small>
        <% end %>
      </h3>
      <hr>
      <ul class="user-info-detial">
        <% unless @user.motto.nil? %>
        <li>
          <span class="user-info-icon">
            <i class="fa fa-volume-up"></i>
          </span>
          <span>
            <%= @user.motto.truncate(30) %>
          </span>
        </li>
        <% end %>
        <li>
          <span class="user-info-icon">
            <i class="fa fa-envelope"></i>
          </span> 
          <span>
            <%= @user.email %>
          </span>
        </li>
        <% unless @user.blog.nil? %>
          <li>
            <span class="user-info-icon">
              <i class="fa fa-link"></i>
            </span> 
            <span>
              <%= link_to(@user.blog.truncate(27), @user.blog) %>
            </span>
          </li>
        <% end %>
        <li>
          <span class="user-info-icon">
            <i class="fa fa-clock-o"></i>
          </span>
          <span>
            <%= @user.join_time.strftime("%Y年%m月%d") %>加入
          </span>
        </li>
      </ul>
      <hr>
      <div class="row">
        <div class="col-md-6 user-follow follower">
          <a href="/users/follower/<%= @user.id %>" title="关注者">
            <span>关注者</span><br>
            <strong id="follower"><%= @user.follower.count%></strong>
            <label> 人</label>
          </a>
        </div>
        <div class="col-md-6 user-follow">
          <a href="/users/followed/<%= @user.id %>" title="关注了">
            <span>关注了</span><br>
            <strong><%= @user.following.count%></strong>
            <label> 人</label>
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="row custom-well my-achieve">
        <div class="row">
          <div class="col-md-9 zhanjiyilan">
            <h3>战绩一览</h3>
          </div>
          <% unless current_user?(@user) %>
            <div class="col-md-3">
              <% unless current_user.nil? %>
                <% unless(current_user.following.include?(@user)) %>
                  <%= link_to "关注", follow_user_path(@user), remote: true, method: :post, :class => "btn btn-sm custom-btn pull-right", :id => "following-#{@user._id}" %>
                <% else %>
                  <%= link_to "取消关注", unfollow_user_path(@user), remote: true, method: :post, :class => "btn btn-sm custom-btn pull-right", :id => "following-#{@user._id}" %>
                <% end %>
              <% else %>
                <%= link_to "关注", signin_path, :class => "btn btn-sm custom-btn pull-right" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <hr>
        <div class="col-md-12 row">
          <div class="col-md-3">
            <i class="fa fa-space-shuttle"></i>
            <span>战斗 <%= @user.battle_count %> </span>
          </div>
          <div class="col-md-3">
            <i class="fa fa-smile-o"></i>
            <span>胜利 <%= @user.win_times %> </span>
          </div>
          <div class="col-md-3">
            <i class="fa fa-frown-o"></i>
            <span>平局 <%= @user.draw_times %> </span>
          </div>
        </div>
        <div class="col-md-12 row">
          <!-- <div class="col-md-3">
            <i class="fa fa-arrow-circle-up"></i>
            <span>排名 25 </span>
          </div> -->
          <div class="col-md-3">
            <i class="fa fa-rocket"></i>
            <span>机甲 <%= @user.meches.count %> </span>
          </div>
          <div class="col-md-3">
            <i class="fa fa-frown-o"></i>
            <span>失败 <%= @user.fail_times %> </span>
          </div>
          <div class="col-md-3">
            <i class="fa fa-plus-circle"></i>
            积分 <span id="my-score"><%= @user.score %> </span>
          </div>
        </div>
      </div>
      <div class="custom-well">
      <h3>拥有的机甲</h3>
      <hr>
      <% @user.meches_per_page(params[:page]).each do |mech| %>
        <div class="row">
          <div class="col-md-12">
            <div class="my-mech-head">
              <span class="my-mech-name">
                <%= link_to(mech.name.nil? ? "无名英雄" : mech.name, mech) %> &nbsp;
                <% if !current_user?(mech.user) %>
                  <% if mech.state == "SUCCESS" %>
                    <% unless signed_in? %>
                      <%= link_to "与之战斗", signin_path ,:class => "btn btn-sm custom-btn"%>
                    <% else %>
                      <a href="#" class="btn btn-sm custom-btn" data-toggle="modal" data-target="#myMech-<%=mech._id %>">与之战斗</a>
                      <div class="modal fade" id="myMech-<%=mech._id %>" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                              <h4 class="modal-title" id="ModalLabel">选择一个自己的机甲</h4>
                            </div>
                            <div class="modal-body row">
                              <div class="container-fluid row col-md-12">
                                <% if my_meches = current_user.meches.where(:state => "SUCCESS").all %>
                                  <% my_meches.each do |m| %>
                                    <center class="col-md-4 choise-my-mech">
                                      <a href="/battle/<%= mech._id%>/<%= m._id %>" data-method="post"><%= m.name %></a>
                                    </center>
                                  <% end %>
                                <% else %>
                                  <center>暂无可战斗机甲，快去添加吧</center>
                                <% end %>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <% else %>
                  <%= link_to "更新机甲", edit_mech_path(mech),
                                  :class => "btn btn-sm custom-btn" %>
                <% end %>
              </span>
              <span class="pull-right my-mech-create-at"><%= time_ago_in_words(mech.create_at) + "前创建" %></span>
            </div>
            <br>
            <div class="my-mech-body">
              <div class="my-mech-info">
                <p>
                <strong><i class="fa fa-space-shuttle"></i> </strong>战斗：<%= mech.battles.count %> / 
                <strong><i class="fa fa-smile-o"></i> 胜利：</strong><%= mech.win_times %> / 
                <strong><i class="fa fa-frown-o"></i> 失败：</strong><%= mech.fail_times %>
                </p>
                <!-- <p><strong><i class="fa fa-smile-o"></i> 胜利：</strong><%#= mech.win_times %></p>
                <p><strong><i class="fa fa-frown-o"></i> 失败：</strong><%#= mech.fail_times %></p> -->
                <p><strong><i class="fa fa-rocket"></i> 机甲引擎：</strong><%= link_to(mech.engine_info.name, mech.engine_info) unless mech.engine_info.nil? %></p>
                <p><strong><i class="fa fa-bomb"></i> 机甲武器：</strong><%= link_to(mech.weapon_info.name, mech.weapon_info) unless mech.weapon_info.nil? %></p>
                <p><strong><i class="fa fa-volume-up"></i> 战斗宣言：</strong><%= mech.manifesto%></p>
                <p><strong><i class="fa fa-bar-chart"></i> 机甲状态：</strong>
                  <% if mech.state == "SUCCESS" %>
                    <% if mech.protect_time + mech.protect_begin_time >= Time.now.to_i %>
                      <span id="mech-state-iden" style="color:green;">护盾保护中，剩余时间：<%= time_ago_in_words(Time.at(mech.protect_begin_time + mech.protect_time)) %></span>
                    <% else %>
                      <span id="mech-state-iden" style="color:red;">备战中</span>
                    <% end %>
                  <% else %>
                    <span style="color:green;">编译失败</span>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
        <hr>
        <% end %>
        <center>
          <%= paginate @user.meches_per_page(params[:page]), :outer_window => 2 %>
        </center>
      </div>
      <div class="row custom-well">
        <h3>参与的战斗</h3>
        <ul class="users">
          <% @user.battles.pop(10).reverse_each do |battle| %>
            <% if battle.defender.user && battle.attacker.user && battle.defender && battle.attacker%>
              <li>
                <span class="col-md-2">
                  <center class="battle-star">
                    <%= battle.starers.count %><br>
                    赞
                  </center>
                </span>
                <span class="col-md-7 battle-info">
                  <div class="battle-info-time">
                    <%= time_ago_in_words(battle.time) + "前" %><br>
                  </div>
                  <div class="battle-info-double">
                    <%= link_to battle.defender.user.name, battle.defender.user %> ::
                    <%= link_to battle.defender.name, battle.defender %>
                    VS 
                    <%= link_to battle.attacker.user.name, battle.attacker.user %> ::
                    <%= link_to battle.attacker.name, battle.attacker %>
                  </div>
                </span>
                <span class="col-md-3">
                  <br>
                  <%= link_to "去观战", battle %>
                </span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>