config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meches
  resources :carriers
  resources :weapons
  resources :battles
  resources :matches

  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout',  to: 'sessions#destory', via: 'delete'
  match '/active', to: 'users#active', via: 'get'
  match '/about', to: 'home#about', via: 'get'
  match '/aboutus', to:'home#aboutus',via: 'get'
  match '/join', to: 'home#join', via: 'get'
  match '/achieve', to: 'home#achieve', via: 'get'
  match '/mechlist', to: 'meches#mech_list', via: 'get'
  match '/reactive', to: 'users#re_active',via: 'get'
  match '/gamebg',to: 'home#gamebg', via: 'get'
  match '/newer',to: 'home#newer', via: 'get'
  match '/download',to: 'home#download', via: 'get'
  match '/stat', to: 'home#stat',via: 'get'
  match '/opensource', to: 'home#opensource', via: 'get'

  match '/users/followed/:id', to: 'users#followed', via: 'get', as: :followed
  match '/users/follower/:id', to: 'users#follower', via: 'get', as: :follower

  match '/meches/stop/:id', to: 'users#stop', via: 'post', as: :stop_mech
  match '/meches/start/:id', to: 'users#start', via: 'post', as: :start_mech

  match '/following/:followed_id', to: 'users#following',via: 'post', as: :follow_user
  match '/unfollowing/:unfollowed_id', to: 'users#unfollowing', via: 'post', as: :unfollow_user

  match '/matches/apply/:id', to: 'matches#apply', via: 'post'
  match '/matches/addmech/:id/:mech_id', to: 'matches#addmech', via: 'post'
  match '/matches/result/:id', to: 'matches#result', via: 'get', as: :match_result
  match '/matches/video/:id', to: 'matches#video', via: 'get', as: :match_rvideo
  match '/matches/genracecard/:id', to: 'matches#gen_racecard', via: 'post', as: :gen_match_racecard
  match '/matches/racecard/:id', to: 'matches#racecard', via: 'get', as: :match_racecard

  match '/battles/download/:id', to: 'battles#download', via: 'get', as: :download_video
  match '/battles/star/:id', to: 'battles#star', via: 'post', as: :star_battle
  match '/battle/:defender_id/:attacker_id', to: 'battles#create', via: 'post'

  match '/video/:id', to: 'home#vedio', via: 'get'
  match '/wondervedio/:id', to: 'home#wondervedio', via: 'get', as: :wonder_vedio
  match '/highlights', to: 'home#wonderful',via: 'get'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :admin_user, only: [:stat]
  def index
  end

  def about
  end

  def aboutus
    
  end

  def join
    
  end

  def achieve
    
  end

  def gamebg
  end

  def newer
  end
  
  def download
  end

  def wonderful
  end

  def stat
  end

  def opensource
  end

  def vedio
    @id = params[:id]
  end

  def wondervedio
    id = params[:id]
    if FileTest::exist?("battle/previous/#{id}.txt")
      send_file "battle/previous/#{id}.txt", :type => 'application/txt'
    else
      render 'public/404.html'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_helper_nav.html.erb
<div class="about-menu">
  <div class="container">
    <a href="/about" title="关于项目" class="about-menu-link <%= 'selected' if current_page?(:action => 'about')%>">关于项目</a>
    <a href="/aboutus" title="关于我们" class="about-menu-link <%= 'selected' if current_page?(:action => 'aboutus')%>">关于我们</a>
    <a href="/achieve" title="机甲日志" class="about-menu-link <%= 'selected' if current_page?(:action => 'achieve')%>">机甲日志</a>
    <a href="/join" title="加入我们" class="about-menu-link <%= 'selected' if current_page?(:action => 'join')%>">加入我们</a>
  </div>
</div>

app/views/home/_main.html.erb
<div id="myCarousel" class="carousel slide" data-interval="2000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('http://ww4.sinaimg.cn/mw1024/9de7f98djw1er9osyawfej218g0rsjz3.jpg')"></div>
            <div class="carousel-caption">
                <h1 class="strong">别样的游戏玩法</h1>
                <h3 class="strong">告别鼠标，用代码操纵你的机甲！</h3>
                <% unless signed_in? %>
                    <%= link_to "立即注册", signin_path, :class => "btn custom-btn2 btn-lg strong"%>
                    <br><br>
                <% end %>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('http://ww1.sinaimg.cn/mw1024/9de7f98djw1er9osvcxn5j218g0p010p.jpg')"></div>
            <div class="carousel-caption">
                <h1 class="strong">人工智能并不遥远</h1>
                <h3 class="strong">制作你专属的智能体，去征战！</h3>
                <a href="/download" title="下载开发包" class="btn custom-btn2 btn-lg strong">下载开发包</a>
                <br><br>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('http://ww1.sinaimg.cn/mw1024/9631b1bbgw1er9nsphirsj218g0xcgsd.jpg')"></div>
            <div class="carousel-caption">
                <h1 class="strong">酷炫的战斗画面</h1>
                <h3 class="strong">让编程不再枯燥，充满乐趣！</h3>
                <!-- <a href="#" title="下载游戏播放器" class="btn custom-btn2 btn-lg">下载游戏播放器</a> -->
                <br><br>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>

<div class="row home-page-top home-page-black">
    <div class="container">
        <div class="row">
            <center class="home-page-newer-title">
                <h2 class="strong">也许，你还是迷茫的新手</h2>
            </center>
            <center class="col-md-4 col-sm-12 home-page-newer-item">
                <a href="/newer" title="新手指南" class="link-unchanged">
                    <div class="newer-item-icon-back">
                        <span class="glyphicon glyphicon-check newer-item-icon" aria-hidden="true"></span>
                    </div>
                </a>
                <!--<img class="img-circle" src="http://ww3.sinaimg.cn/mw1024/9631b1bbgw1erd0g2tjysj205k05k0t0.jpg" alt="新手指南">-->
                <h3>新手指南</h3>
                <p>新手入门，闪电上手</p>
                <!--<a href="/newer" title="新手指南" class="home-link">新手指南 &gt;&gt;</a>-->
            </center>
            <center class="col-md-4 col-sm-12 home-page-newer-item">
                <a href="<%= image_path("document.pdf")%>" title="开发文档" class="link-unchanged">
                    <div class="newer-item-icon-back">
                        <span class="glyphicon glyphicon-folder-open newer-item-icon" aria-hidden="true"></span>
                    </div>
                </a>
                <!--<img class="img-circle" src="http://ww1.sinaimg.cn/mw1024/9631b1bbgw1erd0g2u3hij205k05kmxh.jpg" alt="开发文档">-->
                <h3>开发文档</h3>
                <p>详细开发和游戏手册</p>
                <!--<%= link_to "开发文档 >>", image_path('document.pdf'), :class=>"home-link"%>-->
                <!-- <a href="http://pan.baidu.com/s/1gdgYleN" title="开发文档" class="btn custom-btn btn-lg">开发文档</a> -->
                <!-- <a href="#" title="游戏介绍" class="home-link">查看游戏介绍 &gt;&gt;</a> -->
            </center>
            <center class="col-md-4 col-sm-12 home-page-newer-item">
                <a href="/gamebg" title="游戏背景" class="link-unchanged">
                    <div class="newer-item-icon-back">
                        <span class="glyphicon glyphicon-info-sign newer-item-icon" aria-hidden="true"></span>
                    </div>
                </a>
                <!--<img class="img-circle" src="http://ww4.sinaimg.cn/mw1024/9631b1bbgw1erd0g2wvvaj205k05kdg4.jpg" alt="游戏背景">-->
                <h3>游戏背景</h3>
                <p>机甲帝国的世界观和周边</p>
                <!--<a href="/gamebg" title="游戏背景" class="home-link">游戏背景 &gt;&gt;</a>-->
            </center>
        </div>
    </div>
</div>
<div class="row home-page-gray">
    <div class="container">
        <center class="home-page-newer-title">
            <h2 class="strong">或者，你已是轻车熟路的高手</h2>
        </center>
        <center class="col-md-6 col-sm-12 col-xs-12">
            <%= image_tag('x.png', :class=> "featurette-image img-responsive pull-left")%>
        </center>
        <div class="clear visible-sm visible-xs"></div>
        <center class="col-md-6 col-sm-12 col-xs-12 home-page-content-gray">
            <h3 class="text-center">狄学长大战白骨精</h3>
            <hr class="main-page-hr">
            <h4 class="text-center">狄学长与白骨精酣战 8 个多小时，终于体力不支，倒下了。</h4>
            <center>
                <a href="/highlights" class="btn custom-btn2 btn-lg strong home-page-btn-highlights" title="观看更多精彩战斗">观看更多精彩战斗</a>
            </center>
        </center>
    </div>
</div>

<div class="row home-page-blue">
    <div class="container">
        <center class="home-page-newer-title">
            <h2 class="strong">战斗的号角已经吹响</h2>
            <p class="home-fight-para-1">赶快去创建机甲，征服世界吧！相信你一定会收获别样的精彩！</p>
            <p class="home-fight-para-2">欢迎加入机甲帝国官方QQ群讨论：207730813</p>
        </center>
    </div>
</div>

app/views/home/about.html.erb
<div class="about-main">
</div>
<%= render 'helper_nav'%>
<div class="container main-body custom-well join-us">
  <h2 class="page-header">机甲帝国
    <small>An Amazing Brainstorm</small>
  </h2>
  <h3>了解机甲帝国</h3>
  <p>机甲帝国是一款智能体对战的游戏。</p> 
  <p>玩家可根据官方提供的代码模版编写 AI 代码，上传至机甲帝国对战平台之后即可和其他玩家的 AI 进行对战，获取积分。</p>
  <p>玩家可自由选择一种武器炮塔和一种引擎载具组成战斗机甲，随后战斗在固定地图上发生。</p>
  <br>
  <p>战斗目标是在战斗时限内击毁对方机甲。</p>
  <p>若战斗时限结束仍有多余一个机甲存活, 则胜者为剩余生命值多的机甲。</p>
  <p>对战中若双方同归于尽，则记为平局。</p>
  <br>
  <p>机甲通过使用武器炮塔进行攻击,使用引擎载具进行移动。</p>
  <p>地图上存在若干有冷却时间的军 火库,供机甲补充弹药。</p>
  <p>地图上有若干障碍物,会阻止机甲和子弹的路径。</p>
  <br>
  <h3>项目维护</h3>
  <p>机甲帝国项目由<a href="http://herald.seu.edu.cn"> 东南大学先声网 </a>成员开发。</p>
  <p>项目所有代码托管在<a href="https://github.com/MechEmpire"> Github </a>上。</p>
  <p>我们欢迎任何喜欢机甲帝国的朋友一起来开发和维护机甲帝国，详情请访问<a href="http://mechempire.cn/join">加入我们。</a></p>
  <br>
  <h3>对战平台积分规则</h3>
  <p>采用天梯积分规则。<br>
  <p>天梯采用ELO计算方法，公式参见<a href="http://zh.wikipedia.org/wiki/%E7%AD%89%E7%BA%A7%E5%88%86">wiki。</a><br>
  <p>其中 k = 32 + 16 * 0.9 ^ (双方的比赛场次和)，初始积分为1500分，最小积分为0分，不设上限。
  <br><br>
  <h3>对战平台护盾规则</h3>
  <p>新上传的机甲将获得一天的护盾保护，不接受挑战。</p>
  <p>被攻击失败后将获得5分钟的护盾，不再接受别人挑战。</p>
  <p>处于护盾保护期间的机甲若主动发起攻击将视为放弃护盾。</p>
</div>

app/views/home/aboutus.html.erb
<% provide(:title, '| 关于我们') %>
<div class="aboutus-main">
</div>
<%= render 'helper_nav'%>
<div class="container main-body custom-well">
  <div class="my-temp">
    <h2 class="page-header">团队成员
      <small>Everyone Is Important</small>
    </h2>
    <center>
      <h3> 这里每个人的默默付出, 才让机甲帝国变的更完美</h3>
    </center>
    <br><br>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww3.sinaimg.cn/bmiddle/9631b1bbjw1er9hzdjzgaj202s02sdfp.jpg" alt="">
      <h3>狄学长
          <small>游戏工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww3.sinaimg.cn/bmiddle/9631b1bbjw1er9hzecq6gj207v07v3ym.jpg" alt="">
      <h3>Tairy
          <small>Web 工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww2.sinaimg.cn/mw1024/9631b1bbgw1er9tjrk72jj202s02smx3.jpg" alt="">
      <h3>Scarlett
          <small>UI 设计师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww4.sinaimg.cn/mw1024/9631b1bbjw1er9io9sa30j21991ax7t3.jpg" alt="">
      <h3>菜大肥
          <small>产品经理</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww1.sinaimg.cn/mw1024/9631b1bbjw1er9ixk7ckmj209i09iwep.jpg" alt="">
      <h3>谢峥嵘
          <small>3D 设计师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww2.sinaimg.cn/mw1024/9631b1bbjw1er9igv2y75j209u09t74e.jpg" alt="">
      <h3>姚东成
          <small>Unity3D 工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww3.sinaimg.cn/mw690/841b2879jw1erb7bxg96ij202s02s0sl.jpg" alt="">
      <h3>解曙方
          <small>安全工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww4.sinaimg.cn/mw1024/9631b1bbjw1er9ikohu7ij202y03awee.jpg" alt="">
      <h3>印明亮
          <small>安全工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww4.sinaimg.cn/mw1024/9631b1bbgw1er9xs3htljj202s02sdfn.jpg" alt="">
      <h3>李昕钰
          <small>3D 设计师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww4.sinaimg.cn/mw1024/9631b1bbjw1er9k6toz61j202s02s0sl.jpg" alt="">
      <h3>文轶
          <small>平面设计师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww4.sinaimg.cn/mw1024/9631b1bbjw1er9i72xrlnj202s02s0sk.jpg" alt="">
      <h3>杨宇尘
          <small>平面设计师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww4.sinaimg.cn/bmiddle/9631b1bbgw1erb6rgk9cgj202s02sdfp.jpg" alt="">
      <h3>曹佩哲
          <small>AI 工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww2.sinaimg.cn/mw1024/9631b1bbjw1er9jnlywsjj202s02s3yf.jpg" alt="">
      <h3>何永东
          <small>UI 设计师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww1.sinaimg.cn/mw1024/9631b1bbgw1er9t5wrdfrj20e80e9aak.jpg" alt="">
      <h3>张晖
          <small>Web 前端工程师</small>
      </h3>
    </div>
    <div class="col-lg-3 col-sm-6 text-center">
      <img class="img-circle img-center img-aboutus" src="http://ww2.sinaimg.cn/mw1024/9631b1bbjw1er9iscdzgrj20ib0idtax.jpg" alt="">
      <h3>卢冠男
          <small>Web 后端工程师</small>
      </h3>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/home/achieve.html.erb
<div class="achieve-main">
</div>
<%= render 'helper_nav'%>
<div class="container custom-well main-body">
  <h2 class="page-header">机甲帝国大事记
    <small>That Our Efforts</small>
  </h2>
  <h3>2014.1 至 2014.3</h3>
  <p>战斗核心模块开发</p>
  <p>战斗调试器开发</p>
  <p>战斗 2D 播放器开发</p>
  <h3>2014.3.14 至 2014.4.13</h3>
  <p>第一届机甲帝国比赛在东南大学九龙湖校区举办</p>
  <h3>2015.01 至 2015.04</h3>
  <p>机甲帝国对战平台开发</p>
  <p>机甲 3D 模型开发</p>
  <p>机甲 3D 播放器开发</p>
  <h3>2015.04.20</h3>
  <p>机甲帝国对战平台上线</p>
  <h3>2015.04.24</h3>
  <p>机甲帝国 3D 播放器 Beta 版上线</p>
</div>

app/views/home/download.html.erb
<div class="container main-body custom-well">
  <div class="row">
    <div class="col-lg-12">
    <h1>资源下载</h1>
    <ul class="users">
      <li><a href="http://pan.baidu.com/s/1gddA2gb" title="Flash本地播放器(0505版)">Flash本地播放器(0505版)</a></li>
      <li><a href="http://pan.baidu.com/s/1dD2aUcT" title="Unity3D战斗播放器(抢先版)">Unity3D战斗播放器(抢先版)</a></li>
      <li><a href="http://pan.baidu.com/s/1kTpEbAn" title="开发者手册">开发者手册</a></li>
      <li><a href="http://pan.baidu.com/s/1fhfyA" title="机甲帝国Windows_VS开发包">机甲帝国Windows_VS开发包</a></li>
      <li><a href="http://pan.baidu.com/s/1sjPtfmH" title="机甲帝国Linux开发包">机甲帝国Linux开发包</a></li>
      <li><a href="http://pan.baidu.com/s/1gd2Dwmn" title="示例机甲dll供调试">示例机甲dll供调试</a></li>
    </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'main' %>

app/views/home/join.html.erb
<% provide(:title, '| 加入我们') %>
<div class="join-main">
</div>
<%= render 'helper_nav'%>
<div class="container main-body custom-well">
  <div class="col-lg-12 join-us">
      <h2 class="page-header">加入我们
          <small>Making Your Own Art</small>
      </h2>
      <p>做这一切</p>
      <p>是为了兴趣</p>
      <p>为了满足好奇心</p>
      <!-- <p>提升个人能力</p> -->
      <p>实现有趣的想法</p>
      <p>让生活变的更有意义</p>
      <br>
      <p>如果你也喜欢机甲帝国</p>
      <p>如果你也想学学相关的技术</p>
      <p>如果你也想做做有意思的项目</p>
      <p>就来一起玩吧</p>
      <br>
      <p>远程协作，线上交流</p>
      <p>自我驱动，随时随地工作</p>
      <br>
      <h3>在这里可以学到的</h3>
      <p>游戏设计: 机甲设计, 游戏场景设计</p>
      <p>3D建模: Unity3D机甲建模, 游戏场景建模</p>
      <p>Web开发: Web 前后端技术</p>
      <p>UI设计: Web 页面设计, 平面设计</p>
      <p>AI 开发: 制作最厉害的机甲</p>
      <p>网络安全: 服务器运维，Web安全</p>
      <br>
      <p>联系邮箱 <a href="mailto:join@mechempire.cn?subject=JoinMechempire" "email me">join@mechempire.cn</a> 期待你的加入。</p>
  </div>
</div>

app/views/home/newer.html.erb
<div class="container main-body custom-well">
  <div class="row">
    <div class="col-lg-12 newer">
      <h1>新手指南</h1>
      <hr>
      <p>1. 下载【机甲帝国Windows_VS开发包】，【Flash战斗播放器】（或【Unity3D战斗播放器】），【开发手册】<a href="/download">下载页面</a>。</p>
      <p>2. 双击【机甲帝国战斗调试器.exe】，即可立即生成战斗录像，录像可由【Flash战斗播放器】(或【Unity3D战斗播放器】)播放观看。</p>
      <p>3. 编辑【ConsoleConf.txt】可以配置参战机甲智能体dll路径。</p>
      <p>4. 在【RobotAIFactory】VS 工程模板中编码实现自己的机甲。</p> 
      <p>5. 在 <a href="http://mechempire.cn">mechempire.cn</a> 注册账号，上传代码，与众多机甲一决高下, 赢取妹子的尖叫。</p>
      <!-- <p>6. 参与第二季机甲帝国C++智能体编程争霸赛的联赛，晋级8强，在20150607现场巅峰大战中打败对手，赢取妹子的尖叫。</p> -->
      <p>6. 对战平台积分规则：<br>
      &nbsp;&nbsp;&nbsp;&nbsp;采用天梯积分规则，天梯采用ELO计算方法，公式参见 <a href="http://zh.wikipedia.org/wiki/%E7%AD%89%E7%BA%A7%E5%88%86">wiki</a>。<br>
      &nbsp;&nbsp;&nbsp;&nbsp;其中 k = 32 + 16 * 0.9 ^ (双方的比赛场次和)，初始积分为1500分，最小积分为0分，不设上限。
      </p> 
      <p>7. 对战平台护盾规则： <br> 
      &nbsp;&nbsp;&nbsp;&nbsp;新上传的机甲将获得一天的护盾保护，不接受挑战。<br>
      &nbsp;&nbsp;&nbsp;&nbsp;被攻击失败后将获得5分钟的护盾，不再接受别人挑战。<br>
      &nbsp;&nbsp;&nbsp;&nbsp;处于护盾保护期间的机甲若主动发起攻击将视为放弃护盾。
      </p>
      <p>8. 对战平台英雄榜规则： <br>
      &nbsp;&nbsp;&nbsp;&nbsp;展示平台所有用户。 <br>
      &nbsp;&nbsp;&nbsp;&nbsp;按战斗积分排序。 <br>
      &nbsp;&nbsp;&nbsp;&nbsp;第二季比赛6月1日截止线上初赛。 <br>
      &nbsp;&nbsp;&nbsp;&nbsp;排名前八的机甲进入6月6日决赛巅峰之夜。 <br>
      <p>9.登录东南大学srtp网站报名： <br>
      &nbsp;&nbsp;&nbsp;&nbsp;排行前10%的机甲获得0.5个srtp学分。 <br>
      </p>
      <br><br>
      <blockquote>
        <p>特别提醒：上传至机甲帝国对战平台的代码只需要将 myAI 目录压缩成zip格式的压缩包上传，否则将无法通过服务器编译。</p>
        <p>欢迎加入机甲帝国官方QQ群讨论： 207730813</p>
      </blockquote>
    </div>
  </div>
</div>

app/views/home/opensource.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/styles/monokai_sublime.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<div class="container custom-well main-window">
  <center>
    <h1>代码分享</h1>
    <hr>
  </center>
  <div class="alert alert-warning" role="alert">
    分享的代码仅供参考学习，禁止抄袭，若被发现作禁号，清分，并通报处理。
  </div>
  <br>
  <%= render 'code'%>
</div>

app/views/home/stat.html.erb
<div class="container custom-well main-body">
  用户总数：<%= User.all.count%> <br>
  机甲总数：<%= Mech.all.count%> <br>
  战斗总数：<%= Battle.all.count%> <br>
</div>

app/views/home/vedio.html.erb
<center class="container main-body game-player">
  <embed width="100%" height="600" src="<%= image_path('Battlefield.swf')%>"  flashvars="record_url=<%= wonder_vedio_path(@id) %>" />
  <br><br>
  <%= link_to "战斗录像下载", wonder_vedio_path(@id) %>
</center>