config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meches
  resources :carriers
  resources :weapons
  resources :battles
  resources :matches

  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout',  to: 'sessions#destory', via: 'delete'
  match '/active', to: 'users#active', via: 'get'
  match '/about', to: 'home#about', via: 'get'
  match '/aboutus', to:'home#aboutus',via: 'get'
  match '/join', to: 'home#join', via: 'get'
  match '/achieve', to: 'home#achieve', via: 'get'
  match '/mechlist', to: 'meches#mech_list', via: 'get'
  match '/reactive', to: 'users#re_active',via: 'get'
  match '/gamebg',to: 'home#gamebg', via: 'get'
  match '/newer',to: 'home#newer', via: 'get'
  match '/download',to: 'home#download', via: 'get'
  match '/stat', to: 'home#stat',via: 'get'
  match '/opensource', to: 'home#opensource', via: 'get'

  match '/users/followed/:id', to: 'users#followed', via: 'get', as: :followed
  match '/users/follower/:id', to: 'users#follower', via: 'get', as: :follower

  match '/meches/stop/:id', to: 'users#stop', via: 'post', as: :stop_mech
  match '/meches/start/:id', to: 'users#start', via: 'post', as: :start_mech

  match '/following/:followed_id', to: 'users#following',via: 'post', as: :follow_user
  match '/unfollowing/:unfollowed_id', to: 'users#unfollowing', via: 'post', as: :unfollow_user

  match '/matches/apply/:id', to: 'matches#apply', via: 'post'
  match '/matches/addmech/:id/:mech_id', to: 'matches#addmech', via: 'post'
  match '/matches/result/:id', to: 'matches#result', via: 'get', as: :match_result
  match '/matches/video/:id', to: 'matches#video', via: 'get', as: :match_rvideo
  match '/matches/genracecard/:id', to: 'matches#gen_racecard', via: 'post', as: :gen_match_racecard
  match '/matches/racecard/:id', to: 'matches#racecard', via: 'get', as: :match_racecard

  match '/battles/download/:id', to: 'battles#download', via: 'get', as: :download_video
  match '/battles/star/:id', to: 'battles#star', via: 'post', as: :star_battle
  match '/battle/:defender_id/:attacker_id', to: 'battles#create', via: 'post'

  match '/video/:id', to: 'home#vedio', via: 'get'
  match '/wondervedio/:id', to: 'home#wondervedio', via: 'get', as: :wonder_vedio
  match '/highlights', to: 'home#wonderful',via: 'get'
end

app/models/battle.rb
class Battle
  require 'open4'
  include Mongoid::Document
  include Mongoid::MagicCounterCache
  Mongoid.raise_not_found_error = false 

  field :time,  type: DateTime
  field :result, type: String
  field :defender_id, type: String
  field :attacker_id, type: String
  field :winner_id, type: String
  field :score, type: Integer

  has_and_belongs_to_many :meches
  has_and_belongs_to_many :users, class_name: 'User', inverse_of: :battles
  # counter_cache :users

  belongs_to :match

  has_and_belongs_to_many :starers, class_name: 'User', inverse_of: :stareds
  # counter_cache :starers

  def rand_battle
    # logfile = File.open("test_log.txt","a")
    rand_num = rand()
    # File.open("test_log.txt","a")do |file|  
    #    file.puts rand_num
    # end 
    # logger.error(rand_num)
    # logfile.puts rand_num
    if rand_num > 0.5
      battle_result = self.battle(self.defender,self.attacker)
      # logfile.puts "defender,attacker"
    else
      battle_result = self.battle(self.attacker,self.defender)
      # logfile.puts "attacker,defender"
    end

    if !battle_result
      return false
    end
    # logfile.puts self.winner_id
    # logfile.puts self.attacker_id
    if self.winner_id == self.attacker_id
      # logfile.puts "protect"
      self.defender.update_attributes(:protect_begin_time => Time.now.to_i,
                                      :protect_time => 300)
    end
    # logfile.puts "---"
    # logfile.close
    return true
  end

  def battle(first_mech,second_mech)
    #run battle in sandbox
    pid, stdin, stdout, stderr = Open4.popen4("battle/battle.sh #{first_mech.code_dir}libmyAI.so #{second_mech.code_dir}libmyAI.so #{self._id}")
    ignored, status = Process::waitpid2 pid
    # logger.error(stderr.read)
    #get battle result

    pid, stdin, stdout, stderr = Open4.popen4("battle/result.sh #{first_mech.code_dir}libmyAI.so #{second_mech.code_dir}libmyAI.so #{self._id}")
    ignored, status = Process::waitpid2 pid


    if FileTest::exists?("battle/result/#{self._id}.xml")
      x = File.read("battle/result/#{self._id}.xml")
    else
      return false
    end

    # x = File.read("battle/result/#{self._id}.xml")
    winnerID = Hash.from_xml(x)['battleStatistics']['winnerID']

    sa = 0.0
    sb = 0.0

    if winnerID == "0"
      sb = 1.0
      self.winner_id = first_mech._id #self.defender_id
      first_mech.update_attributes(:score => first_mech.score + 3,
                                    :win_times => first_mech.win_times + 1)
      first_mech.user.update_attributes(:win_times => first_mech.user.win_times + 1,
                                      :battle_count => first_mech.user.battle_count + 1)

      second_mech.update_attributes(:score => second_mech.score - 1,
                                      :fail_times => second_mech.fail_times + 1)

      second_mech.user.update_attributes(:fail_times => second_mech.user.fail_times + 1,
                                      :battle_count => second_mech.user.battle_count + 1)
    elsif winnerID == "1"
      sa = 1.0
      self.winner_id = second_mech._id
      second_mech.update_attributes(:score => second_mech.score + 3,
                                      :win_times => second_mech.win_times + 1)
      second_mech.user.update_attributes(:win_times => second_mech.user.win_times + 1,
                                      :battle_count => second_mech.user.battle_count + 1)

      first_mech.update_attributes(:score => first_mech.score - 1,
                                      :fail_times => first_mech.fail_times + 1)
      
      first_mech.user.update_attributes(:fail_times => first_mech.user.fail_times + 1,
                                        :battle_count => first_mech.user.battle_count + 1)
    elsif winnerID == "-1"
      sa = sb = 0.5
      self.winner_id = nil
      second_mech.update_attribute("draw_times", second_mech.draw_times + 1)
      second_mech.user.update_attributes(:draw_times => second_mech.user.draw_times + 1,
                                         :battle_count => second_mech.user.battle_count + 1)

      first_mech.update_attribute("draw_times", first_mech.draw_times + 1)
      first_mech.user.update_attributes(:draw_times => first_mech.user.draw_times + 1,
                                        :battle_count => first_mech.user.battle_count + 1)

    end

    ra = second_mech.user.score
    rb = first_mech.user.score
    ea = 1.0 / (1.0 + 10 **( (rb-ra)/400.0 ) )
    eb = 1.0 / (1.0 + 10 **( (ra-rb)/400.0 ) )
    k = 32 + 16 * (0.9 ** (first_mech.user.battle_count + second_mech.user.battle_count ))
    ra = ra + k * (sa - ea)
    rb = rb + k * (sb - eb)
    if ra < 0
      ra = 0
    end
    if rb < 0
      rb = 0
    end

    self.score = (k * (sa - ea)).abs

    second_mech.user.update_attribute("score", ra.round)
    first_mech.user.update_attribute("score", rb.round)

    # logger.error(stderr.read)
  end

  def defender
    Mech.find(self.defender_id)
  end

  def attacker
    Mech.find(self.attacker_id)
  end

  def winner
    Mech.find(self.winner_id)
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: [:show, :download, :star, :destroy]
  before_action :actived_user, only: [:create, :destroy]
  before_action :admin_user, except: [:create, :download, :index, :show, :star]
  before_action :signed_in_user, only: [:star, :create, :destroy]
  before_action :locked_user

  def index
    # @battles = Battle.order("time DESC").page(params[:page]).per(10)
    @battles = Battle.order("time DESC").where(:mech_ids.ne => nil).page(params[:page]).per(30)
  end

  def new
  end

  def create
    defender = Mech.find(params['defender_id'])
    attacker = Mech.find(params['attacker_id'])
    store_location

    if defender.nil? || attacker.nil?
      respond_to do |format|
        flash[:danger] = "机甲参数错误"
        format.html { redirect_to defender}
        # format.json { render json: @battle.errors, status: :unprocessable_entity }
        return
      end
    end

    if defender.state != "SUCCESS" && attacker.state != "SUCCESS"
      respond_to do |format|
        flash[:danger] = "机甲状态不可战"
        format.html { redirect_to defender}
        # format.json { render json: @battle.errors, status: :unprocessable_entity }
        return
      end
    end

    if defender.protect_begin_time + defender.protect_time >= Time.now.to_i
      respond_to do |format|
        flash[:danger] = "攻击机甲处于护盾保护状态，无法战斗"
        format.html { redirect_to defender}
        # format.json { render json: @battle.errors, status: :unprocessable_entity }
        return
      end
    end

    if attacker.protect_begin_time + attacker.protect_time >= Time.now.to_i
      attacker.update_attribute("protect_time", 0)
    end

    @battle = Battle.new(:defender_id => defender._id,
                         :attacker_id => attacker._id,
                         :time => Time.now)

    if !@battle.save
      respond_to do |format|
        flash[:danger] = "战斗数据写入失败"
        format.html { redirect_back_or(root_path)}
        format.json { render json: @battle.errors, status: :unprocessable_entity }
        return
      end
    end

    if !@battle.rand_battle
      respond_to do |format|
        flash[:danger] = "战斗程序运行失败"
        format.html { redirect_to defender }
        @battle.destroy
        # format.json { render json: @battle.errors, status: :unprocessable_entity }
        return
      end
    end

    defender.battles << @battle
    attacker.battles << @battle

    defender.user.battles << @battle
    attacker.user.battles << @battle

    respond_to do |format|
      format.html { redirect_to @battle, notice: '战斗成功，观看战斗结果！' }
      format.json { render :show, status: :created, location: @battle }
    end
  end

  def destroy
    @battle.destroy
    respond_to do |format|
      format.html { redirect_to battles_url, notice: '删除用户成功!' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def star
    respond_to do |format|
      if !@battle.starers.include?(current_user)
        @battle.starers << current_user
        format.js
      else
        format.js do 
          render js:"alert('点赞失败')"
        end
      end
    end
  end

  def download
    send_file "battle/result/#{@battle._id}.txt", :type => 'application/txt'
  end

  private

    def set_battle
      @battle = Battle.find(params[:id])
      if @battle.nil?
        render :file => 'public/404.html'
      end
    end
    # def battle_params
    #   params.require(:battle).permit(:attacker_id,
    #                                  :defender_id)
    # end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/create.html.erb
<center class="container main-body custom-well">
<div class="dialog main-body">
  <div>
    <h1>战斗出错啦！</h1>
    <p>战斗出错了哦，换个姿势试试吧！</p>
  </div>
</div>
</center>

app/views/battles/index.html.erb
<center class="container main-body custom-well">
  <h1>实时战况</h1>
  <ul class="users">
    <% @battles.each do |battle| %>
      <% if battle.defender && battle.attacker && battle.defender.user && battle.attacker.user%>
        <li>
          <span class="col-md-2">
            <div class="battle-star">
              <%= battle.starers.count %><br>
              赞
            </div>
          </span>
          <span class="col-md-8 battle-info">
            <div class="battle-info-time">
              <%= time_ago_in_words(battle.time) + "前" %><br>
            </div>
            <div class="battle-info-double">
              <%= link_to battle.attacker.user.name, battle.attacker.user %> ::
              <%= link_to battle.attacker.name, battle.attacker %>
              攻击
              <%= link_to battle.defender.user.name, battle.defender.user %> ::
              <%= link_to battle.defender.name, battle.defender %>
              <% if battle.winner_id == battle.attacker_id %>
                <span style="color:red;">
                  <% unless battle.score.nil? %>
                    成功, 积分 +
                    <%= battle.score %>
                  <% end %>
                </span>
              <% elsif battle.winner_id.nil? %>
                平局
              <% else %>
                <span style="color:green;">
                <% unless battle.score.nil? %>
                  失败, 积分 -
                  <%= battle.score %>
                <% end %>
              <% end %>
            </div>
          </span>
          <span class="col-md-2">
            <br>
            <%= link_to "去观战", battle , :class => "btn btn-sm custom-btn pull-right" %>
          </span>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= paginate @battles, :outer_window => 2 %>
</center>

app/views/battles/new.html.erb
<h1>Battles#new</h1>
<p>Find me in app/views/battles/new.html.erb</p>

app/views/battles/show.html.erb
<center class="container main-body game-player">
  <h2>
    <%= link_to @battle.defender.user.name, @battle.defender.user %> ::
    <%= link_to @battle.defender.name, @battle.defender %>
    VS 
    <%= link_to @battle.attacker.user.name, @battle.attacker.user %> ::
    <%= link_to @battle.attacker.name, @battle.attacker %>
  </h2>
  <hr>
  <% if !current_user.nil? && current_user.admin? %>
    <%= link_to "删除战斗", @battle, method: :delete,
                                  data: { confirm: "确认删除吗？" } %>
  <% end %>
  <embed width="100%" height="600" src="<%= image_path('Battlefield.swf')%>"  flashvars="record_url=<%= download_video_path(@battle) %>" />
  <br><br>
  <%= link_to "战斗录像下载", download_video_path(@battle) %>
  <% if signed_in? %>
    <% if @battle.starers.include?(current_user) %>
      <a href="javascript:void(0);" title="已赞" class="btn btn-default custom-btn">已赞</a>
    <% else %>
      <%= link_to "点赞", star_battle_path(@battle), :id => "star",:class => "btn btn-default custom-btn" , :remote => true, :method => "post"%>
    <% end %>
  <% else %>
    <%= link_to "点赞", signin_path, :id => "star",:class => "btn btn-default custom-btn"%>
  <% end %>
</center>

app/views/battles/star.js.erb
$("#star").html("已赞").attr("href","#");

app/views/battles/update.html.erb
<h1>Battles#update</h1>
<p>Find me in app/views/battles/update.html.erb</p>