config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meches
  resources :carriers
  resources :weapons
  resources :battles
  resources :matches

  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout',  to: 'sessions#destory', via: 'delete'
  match '/active', to: 'users#active', via: 'get'
  match '/about', to: 'home#about', via: 'get'
  match '/aboutus', to:'home#aboutus',via: 'get'
  match '/join', to: 'home#join', via: 'get'
  match '/achieve', to: 'home#achieve', via: 'get'
  match '/mechlist', to: 'meches#mech_list', via: 'get'
  match '/reactive', to: 'users#re_active',via: 'get'
  match '/gamebg',to: 'home#gamebg', via: 'get'
  match '/newer',to: 'home#newer', via: 'get'
  match '/download',to: 'home#download', via: 'get'
  match '/stat', to: 'home#stat',via: 'get'
  match '/opensource', to: 'home#opensource', via: 'get'

  match '/users/followed/:id', to: 'users#followed', via: 'get', as: :followed
  match '/users/follower/:id', to: 'users#follower', via: 'get', as: :follower

  match '/meches/stop/:id', to: 'users#stop', via: 'post', as: :stop_mech
  match '/meches/start/:id', to: 'users#start', via: 'post', as: :start_mech

  match '/following/:followed_id', to: 'users#following',via: 'post', as: :follow_user
  match '/unfollowing/:unfollowed_id', to: 'users#unfollowing', via: 'post', as: :unfollow_user

  match '/matches/apply/:id', to: 'matches#apply', via: 'post'
  match '/matches/addmech/:id/:mech_id', to: 'matches#addmech', via: 'post'
  match '/matches/result/:id', to: 'matches#result', via: 'get', as: :match_result
  match '/matches/video/:id', to: 'matches#video', via: 'get', as: :match_rvideo
  match '/matches/genracecard/:id', to: 'matches#gen_racecard', via: 'post', as: :gen_match_racecard
  match '/matches/racecard/:id', to: 'matches#racecard', via: 'get', as: :match_racecard

  match '/battles/download/:id', to: 'battles#download', via: 'get', as: :download_video
  match '/battles/star/:id', to: 'battles#star', via: 'post', as: :star_battle
  match '/battle/:defender_id/:attacker_id', to: 'battles#create', via: 'post'

  match '/video/:id', to: 'home#vedio', via: 'get'
  match '/wondervedio/:id', to: 'home#wondervedio', via: 'get', as: :wonder_vedio
  match '/highlights', to: 'home#wonderful',via: 'get'
end

app/views/layouts/_admin_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/admin"><i class="fa fa-university"></i> 机甲帝国管理员系统</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
            <ul class="dropdown-menu message-dropdown">
                <li class="message-preview">
                    <a href="#">
                        <div class="media">
                            <span class="pull-left">
                                <img class="media-object" src="http://placehold.it/50x50" alt="">
                            </span>
                            <div class="media-body">
                                <h5 class="media-heading"><strong><%= current_user.name %></strong>
                                </h5>
                                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                <p>Lorem ipsum dolor sit amet, consectetur...</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="message-preview">
                    <a href="#">
                        <div class="media">
                            <span class="pull-left">
                                <img class="media-object" src="http://placehold.it/50x50" alt="">
                            </span>
                            <div class="media-body">
                                <h5 class="media-heading"><strong><%= current_user.name %></strong>
                                </h5>
                                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                <p>Lorem ipsum dolor sit amet, consectetur...</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="message-preview">
                    <a href="#">
                        <div class="media">
                            <span class="pull-left">
                                <img class="media-object" src="http://placehold.it/50x50" alt="">
                            </span>
                            <div class="media-body">
                                <h5 class="media-heading"><strong><%= current_user.name %></strong>
                                </h5>
                                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                <p>Lorem ipsum dolor sit amet, consectetur...</p>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="message-footer">
                    <a href="#">Read All New Messages</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
            <ul class="dropdown-menu alert-dropdown">
                <li>
                    <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                </li>
                <li>
                    <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">View All</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#book"><i class="fa fa-fw fa-book"></i> 书籍管理 <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="book" class="collapse">
                  <li>
                      <a href="/books">书籍列表</a>
                  </li>
                  <li>
                      <a href="#">Dropdown Item</a>
                  </li>
              </ul>
            </li>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#users">
                <i class="fa fa-fw fa-users"></i> 用户管理 
                <i class="fa fa-fw fa-caret-down"></i>
              </a>
              <ul id="users" class="collapse">
                <li>
                    <a href="/users">用户列表</a>
                </li>
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#activity"><i class="fa fa-fw fa-connectdevelop"></i> 活动管理 <i class="fa fa-fw fa-caret-down"></i></a>
              <ul id="activity" class="collapse">
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
              </ul>
            </li>
            <li>
                <a href="forms.html"><i class="fa fa-fw fa-cogs"></i> 网站设置</a>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-5 col-xs-7">
        <div class="row2">
          <div class="col-lg-6 col-sm-6 col-xs-12">
            <div class="visible-xs">
              <a href="/"><%=image_tag("logo-foot.png", :height => "60", :style => "margin-bottom: 10px")%></a>
            </div>
            <p>© MechEmpire <%= Time.now.year %></p>
          </div>
          <div class="col-lg-6 col-sm-6 col-xs-12">
            <div class="row2">
              <div class="col-lg-6 col-sm-12 hidden-xs">
                <a href="/about" title="关于我们">关于我们</a>
              </div>
              <div class="col-lg-6 col-sm-12 hidden-xs">
                <a href="/join" title="加入我们">加入我们</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-2 hidden-xs">
        <center>
          <a href="/"><%=image_tag("logo-foot.png", :height => "60", :style => "margin-top: -15px")%></a>
        </center>
      </div>
      <div class="col-lg-4 col-sm-5 col-xs-5 row2" style="text-align: right;">
        <div class="col-xs-12 visible-xs">
          <a href="/about" title="关于我们">关于我们</a>
        </div>
        <div class="col-xs-12 visible-xs">
          <a href="/join" title="加入我们">加入我们</a>
        </div>
        <div class="col-xs-12 visible-xs">
          <br />
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-12">
          <a href="/mechlist" title="装备介绍">装备介绍</a>
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-12">
          <a href="/newer" title="新手指南">新手指南</a>
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-12">
          <a href="/about" title="游戏介绍">游戏介绍</a>
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-12">
          <a href="/download" title="资源下载">资源下载</a>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1254816734'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s95.cnzz.com/z_stat.php%3Fid%3D1254816734%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top mech-nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/"><%=image_tag("mech-logo-s.png",:class => "mech-nav-logo")%></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
      <ul class="nav navbar-nav">
        <li>
          <a href="/">首页</a>
        </li>
        <li>
          <a href="/mechlist">装备介绍</a>
        </li>
        <li>
          <a href="/users">英雄榜</a>
        </li>
        <li>
          <a href="/battles">实时战况</a>
        </li>
        <li>
          <a href="/highlights">精彩战斗</a>
        </li>
        <li>
          <a href="/opensource">代码分享</a>
        </li>
        <li>
          <a href="/download">资源下载</a>
        </li>
         <li>
          <a href="http://mc.mechempire.cn">Minecraft</a>
        </li>
        <li>
          <a href="/about" class="hidden-sm">关于</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
              <i class="fa fa-user"></i> 
              <%= current_user.name %> 
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "个人主页", current_user %></li>
              <li><%= link_to "设置", edit_user_path(current_user) %></li>
              <li><%= link_to "创建机甲", new_mech_path %></li>
              <li class="divider"></li>
              <% if current_user.admin? %>
                <li><%= link_to "添加载具", new_carrier_path %></li>
                <li><%= link_to "添加武器", new_weapon_path %></li>
                <li><%= link_to "创建比赛", new_match_path %></li>
                <li><%= link_to "管理机甲", meches_path %></li>
                <li><a href="/stat" title="数据中心">数据中心</a></li>
                <li class="divider"></li>
              <% end %>
              <li>
                <%= link_to "登出", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "注册", signup_path %></li>
          <li><%= link_to "登录", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_ie.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>机甲帝国-管理员系统</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render 'layouts/ie' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      <%= value %>
    </div>
  <% end %>
  <div id="wrapper">
    <!-- Navigation -->
    <%= render 'layouts/admin_nav' %>
    <div id="page-wrapper">
      <div class="container-fluid">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="mechempire">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>机甲帝国-MechEmpire</title>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    <%= value %>
  </div>
<% end %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= javascript_include_tag 'application'%>
</body>
</html>